### PR TITLE
Header

### PR DESCRIPTION
**Pull request by vasyl-n**

### CODE REVIEW

**Comment by mjraybk07** [comment]
Scaling of the full page has been lost in this version.  'container' div is the grid parent for the full page layout.  note that grid attributes are only passed from the parent container to its immediate children. previously, 'nav-left/center/right' were the immediate children of 'container' but the introduction of 'AppHeader' (with new css styles) has cut the nav containers from their grid properties. Consider copying some of the 'nav' grid and flex styling to AppHeader (e.g. to span the AppHeader across the page.. grid-area: 1/1/2/4, then set the max height, display flex, flex direction row )

**Comment by vasyl-n** [comment]
Seems like problem is not with a header. Page doesn't scale even without it (
it was broken before I started header ).  I think we need to fix this
separately.

**Comment by vasyl-n** [comment]
@mjraybk07 also it looks like header is in a grid. it takes first row. and three columns

**Review by mjraybk07 — APPROVED** [review]
ok sounds good

**Review by echi81 — APPROVED** [review]

**Pull request merged**
